real_mvp_achievements = ScriptThread("real_mvp_achievements") 


function real_mvp_achievements:Run()
    local playerPedId = {0, 1, 2}
    
    while self:IsRunning() do
        if IsKeyDown(0x61) then
		-- KEY: Numpad1
		for i= 1, 3 do
	--
					natives.STATS.STAT_SET_BOOL(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_AWD_FMATTGANGHQ"), true, true)
					natives.STATS.STAT_SET_BOOL(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_AWD_FMFULLYMODDEDCAR"), true, true)
					natives.STATS.STAT_SET_BOOL(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_AWD_FMKILL3ANDWINGTARACE"), true, true)
					natives.STATS.STAT_SET_BOOL(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_AWD_FMMOSTKILLSSURVIVE"), true, true)
					natives.STATS.STAT_SET_BOOL(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_AWD_FMPICKUPDLCCRATE1ST"), true, true)
					natives.STATS.STAT_SET_BOOL(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_AWD_FMRACEWORLDRECHOLDER"), true, true)
					natives.STATS.STAT_SET_BOOL(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_AWD_FMWINALLRACEMODES"), true, true)
					natives.STATS.STAT_SET_BOOL(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_AWD_FMWINEVERYGAMEMODE"), true, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_ADVRIFLE_ENEMY_KILLS"), 600, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_ADVRIFLE_KILLS"), 600, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_APPISTOL_ENEMY_KILLS"), 600, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_APPISTOL_KILLS"), 600, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_ASLTRIFLE_ENEMY_KILLS"), 600, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_ASLTRIFLE_KILLS"), 600, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_ASLTSHTGN_ENEMY_KILLS"), 600, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_ASLTSHTGN_KILLS"), 600, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_ASLTSMG_ENEMY_KILLS"), 600, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_ASLTSMG_KILLS"), 600, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_AWD_20_KILLS_MELEE"), 50, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_AWD_25_KILLS_STICKYBOMBS"), 50, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_AWD_50_KILLS_GRENADES"), 50, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_AWD_CAR_BOMBS_ENEMY_KILLS"), 25, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_AWD_ENEMYDRIVEBYKILLS"), 600, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_AWD_FMBBETWIN"), 50000, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_AWD_FMHORDWAVESSURVIVE"), 21, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_AWD_FMKILLBOUNTY"), 50, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_AWD_FMRALLYWONDRIVE"), 10,true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_AWD_FMRALLYWONDRIVE"), 2, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_AWD_FMREVENGEKILLSDM"), 60, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_AWD_FMWINAIRRACE"), 2, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_AWD_FMWINSEARACE"), 10,true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_AWD_FM_DM_TOTALKILLS"), 500, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_AWD_FM_DM_WINS"), 63, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_AWD_FM_GOLF_WON"), 2, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_AWD_FM_GTA_RACES_WON"), 12, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_AWD_FM_RACES_FASTEST_LAP"), 101, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_AWD_FM_SHOOTRANG_CT_WON"), 2, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_AWD_FM_SHOOTRANG_GRAN_WON"), 2, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_AWD_FM_SHOOTRANG_RT_WON"), 2, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_AWD_FM_SHOOTRANG_TG_WON"), 2, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_AWD_FM_TDM_MVP"), 60, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_AWD_FM_TDM_WINS"), 13, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_AWD_FM_TENNIS_WON"), 2, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_AWD_HOLD_UP_SHOPS"), 20, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_AWD_NO_ARMWRESTLING_WINS"), 21, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_AWD_RACES_WON"), 101, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_AWD_SECURITY_CARS_ROBBED"), 40, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CMBTMG_ENEMY_KILLS"), 600, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CMBTMG_KILLS"), 600, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CMBTPISTOL_ENEMY_KILLS"), 600, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CMBTPISTOL_KILLS"), 600, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CRBNRIFLE_ENEMY_KILLS"), 600, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CRBNRIFLE_KILLS"), 600, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_DB_PLAYER_KILLS"), 1000, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_GRENADE_ENEMY_KILLS"), 50, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_GRNLAUNCH_ENEMY_KILLS"), 600, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_GRNLAUNCH_KILLS"), 600, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_HVYSNIPER_ENEMY_KILLS"), 600, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_HVYSNIPER_KILLS"), 600, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_KILLS_PLAYERS"), 1000, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_LAP_DANCED_BOUGHT"), 50, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_MG_ENEMY_KILLS"), 600, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_MG_KILLS"), 600, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_MICROSMG_ENEMY_KILLS"), 600, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_MICROSMG_KILLS"), 600, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_MINIGUNS_ENEMY_KILLS"), 600, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_MINIGUNS_KILLS"), 600, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_NUMBER_SLIPSTREAMS_IN_RACE"), 110,true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_NUMBER_TURBO_STARTS_IN_RACE"), 100, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_PISTOL_ENEMY_KILLS"), 600, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_PISTOL_KILLS"), 600, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_PLAYER_HEADSHOTS"), 623, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_PUMP_ENEMY_KILLS"), 600, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_PUMP_KILLS"), 600, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_RACES_WON"), 100, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_RACES_WON"), 50,true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_RPG_ENEMY_KILLS"), 600, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_RPG_KILLS"), 600, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_SAWNOFF_ENEMY_KILLS"), 600, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_SMG_ENEMY_KILLS"), 600, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_SMG_KILLS"), 600, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_SNIPERRFL_ENEMY_KILLS"), 600, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_SNIPERRFL_KILLS"), 600, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_USJS_COMPLETED"), 50, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_USJS_FOUND"), 50,true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MPPLY_DM_TOTAL_DEATHS"), 412, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MPPLY_TENNIS_MATCHES_WON"), 2, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MPPLY_TIMES_FINISH_DM_TOP_3"), 36, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MPPLY_TIMES_RACE_BEST_LAP"), 101, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MPPLY_TOTAL_DEATHMATCH_LOST"), 23, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MPPLY_TOTAL_RACES_LOST"), 36, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MPPLY_TOTAL_RACES_WON"), 101, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MPPLY_TOTAL_TDEATHMATCH_WON"), 63, true)
					
	-- End of hashes.

        end
		print("You have successfully received all achievements.")
		end
            self:Wait(50)
    end
end

function real_mvp_achievements:OnError()
    print("You done failed son!")
    self:Reset()
end

real_mvp_achievements:Register()