real_mvp = ScriptThread("real_mvp") 


function real_mvp:Run()
    local playerPedId = {0, 1, 2}
    
    while self:IsRunning() do
        if IsKeyDown(110) then
		for i= 1, 3 do
		-- 110 = DEL
print("Converting stats and unlocks...")
-- Level Stat. This is based on the amount of XP per level. It will now apply global XP. Do note that if you have several characters you will need to combine all of their XP earned for your correct global XP value.
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CHAR_XP_FM"), 2284550, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MPPLY_GLOBALXP"), 2284550, true)
-- Unlocks and achievements.
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_RACES_WON"), 50,true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_NUMBER_SLIPSTREAMS_IN_RACE"), 110,true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_NUMBER_TURBO_STARTS_IN_RACE"), 90,true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_AWD_FMWINSEARACE"), 10,true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_AWD_FMWINAIRRACE"), 1,true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_AWD_FM_RACES_FASTEST_LAP"), 50,true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_USJS_FOUND"), 50,true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_USJS_COMPLETED"), 50,true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_AWD_FMRALLYWONDRIVE"), 10,true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_SAWNOFF_ENEMY_KILLS"), 600, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_SCRIPT_INCREASE_STAM"), 100, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_SCRIPT_INCREASE_STRN"), 100, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_SCRIPT_INCREASE_LUNG"), 100, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_SCRIPT_INCREASE_DRIV"), 100, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_SCRIPT_INCREASE_FLY"), 100, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_SCRIPT_INCREASE_SHO"), 100, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_SCRIPT_INCREASE_STL"), 100, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_RACES_WON"), 100, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_PISTOL_KILLS"), 600, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CMBTPISTOL_KILLS"), 600, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_APPISTOL_KILLS"), 600, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_MICROSMG_KILLS"), 600, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_SMG_KILLS"), 600, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_ASLTSMG_KILLS"), 600, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_ASLTRIFLE_KILLS"), 600, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CRBNRIFLE_KILLS"), 600, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_ADVRIFLE_KILLS"), 600, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_HVYSNIPER_KILLS"), 600, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_SNIPERRFL_KILLS"), 600, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_ASLTSHTGN_KILLS"), 600, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_PUMP_KILLS"), 600, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_GRNLAUNCH_KILLS"), 600, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_RPG_KILLS"), 600, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_MINIGUNS_KILLS"), 600, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_ASLTSMG_KILLS"), 600, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_ASLTRIFLE_KILLS"), 600, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CRBNRIFLE_KILLS"), 600, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_ADVRIFLE_KILLS"), 600, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_HVYSNIPER_KILLS"), 600, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_SNIPERRFL_KILLS"), 600, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_MG_KILLS"), 600, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CMBTMG_KILLS"), 600, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_PISTOL_ENEMY_KILLS"), 600, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CMBTPISTOL_ENEMY_KILLS"), 600, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_APPISTOL_ENEMY_KILLS"), 600, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_MICROSMG_ENEMY_KILLS"), 600, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_SMG_ENEMY_KILLS"), 600, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_ASLTSMG_ENEMY_KILLS"), 600, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_ASLTRIFLE_ENEMY_KILLS"), 600, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CRBNRIFLE_ENEMY_KILLS"), 600, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_ADVRIFLE_ENEMY_KILLS"), 600, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_HVYSNIPER_ENEMY_KILLS"), 600, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_SNIPERRFL_ENEMY_KILLS"), 600, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_ASLTSHTGN_ENEMY_KILLS"), 600, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_PUMP_ENEMY_KILLS"), 600, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_GRNLAUNCH_ENEMY_KILLS"), 600, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_RPG_ENEMY_KILLS"), 600, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_MINIGUNS_ENEMY_KILLS"), 600, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_ASLTSMG_ENEMY_KILLS"), 600, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_ASLTRIFLE_ENEMY_KILLS"), 600, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CRBNRIFLE_ENEMY_KILLS"), 600, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_ADVRIFLE_ENEMY_KILLS"), 600, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_HVYSNIPER_ENEMY_KILLS"), 600, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_SNIPERRFL_ENEMY_KILLS"), 600, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_MG_ENEMY_KILLS"), 600, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CMBTMG_ENEMY_KILLS"), 600, true)
natives.STATS.STAT_SET_BOOL(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_AWD_FMRACEWORLDRECHOLDER"), true, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_AWD_ENEMYDRIVEBYKILLS"), 600, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_USJS_COMPLETED"), 50, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_USJS_FOUND"), 50, true)
natives.STATS.STAT_SET_BOOL(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_AWD_FMWINALLRACEMODES"), true, true)
natives.STATS.STAT_SET_BOOL(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_AWD_FMWINEVERYGAMEMODE"), true, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_DB_PLAYER_KILLS"), 1000, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_KILLS_PLAYERS"), 1000, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_AWD_FMHORDWAVESSURVIVE"), 21, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_AWD_CAR_BOMBS_ENEMY_KILLS"), 25, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_AWD_FM_TDM_MVP"), 60, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_AWD_HOLD_UP_SHOPS"), 20, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_AWD_RACES_WON"), 101, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_AWD_NO_ARMWRESTLING_WINS"), 21, true)
natives.STATS.STAT_SET_BOOL(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_AWD_FMATTGANGHQ"), true, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_AWD_FMBBETWIN"), 50000, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_AWD_FM_DM_WINS"), 51, true)
natives.STATS.STAT_SET_BOOL(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_AWD_FMFULLYMODDEDCAR"), true, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_AWD_FM_DM_TOTALKILLS"), 500, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_MPPLY_DM_TOTAL_DEATHS"), 412, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_MPPLY_TIMES_FINISH_DM_TOP_3"), 36, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_PLAYER_HEADSHOTS"), 623, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_AWD_FM_DM_WINS"), 63, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_AWD_FM_TDM_WINS"), 13, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_AWD_FM_GTA_RACES_WON"), 12, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_AWD_FM_GOLF_WON"), 2, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_AWD_FM_SHOOTRANG_TG_WON"), 2, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_AWD_FM_SHOOTRANG_RT_WON"), 2, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_AWD_FM_SHOOTRANG_CT_WON"), 2, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_AWD_FM_SHOOTRANG_GRAN_WON"), 2, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_AWD_FM_TENNIS_WON"), 2, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_MPPLY_TENNIS_MATCHES_WON"), 2, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_MPPLY_TOTAL_TDEATHMATCH_WON"), 63, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_MPPLY_TOTAL_RACES_WON"), 101, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_MPPLY_TOTAL_DEATHMATCH_LOST"), 23, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_MPPLY_TOTAL_RACES_LOST"), 36, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_AWD_25_KILLS_STICKYBOMBS"), 50, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_AWD_50_KILLS_GRENADES"), 50, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_GRENADE_ENEMY_KILLS"), 50, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_AWD_20_KILLS_MELEE"), 50, true)
natives.STATS.STAT_SET_BOOL(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_AWD_FMMOSTKILLSSURVIVE"), true, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_AWD_FMRALLYWONDRIVE"), 2, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_AWD_FMWINSEARACE"), 2, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_AWD_FMWINAIRRACE"), 2, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_MPPLY_TIMES_RACE_BEST_LAP"), 101, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_NUMBER_TURBO_STARTS_IN_RACE"), 100, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_AWD_FM_RACES_FASTEST_LAP"), 101, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_NUMBER_SLIPSTREAMS_IN_RACE"), 105, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_MPPLY_OVERALL_CHEAT"), 0, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_LAP_DANCED_BOUGHT"), 50, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_AWD_FMKILLBOUNTY"), 50, true)
natives.STATS.STAT_SET_BOOL(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_AWD_FMKILL3ANDWINGTARACE"), true, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_AWD_FMREVENGEKILLSDM"), 60, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_AWD_SECURITY_CARS_ROBBED"), 40, true)
natives.STATS.STAT_SET_BOOL(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_AWD_FMPICKUPDLCCRATE1ST"), true, true)
natives.STATS.STAT_SET_FLOAT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_MPPLY_OVERALL_BADSPORT"), 0, true)
natives.STATS.STAT_SET_BOOL(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_MPPLY_CHAR_IS_BADSPORT"), false, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_MPPLY_BECAME_BADSPORT_NUM"), 0, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_BAD_SPORT_BITSET"), 0, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CHEAT_BITSET"), 0, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_MPPLY_REPORT_STRENGTH"), 32, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_MPPLY_COMMEND_STRENGTH"), 100, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_MPPLY_FRIENDLY"), 100, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_MPPLY_HELPFUL"), 100, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_MPPLY_GRIEFING"), 0, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_MPPLY_OFFENSIVE_LANGUAGE"), 0, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_MPPLY_OFFENSIVE_UGC"), 0, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_MPPLY_VC_HATE"), 0, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_MPPLY_GAME_EXPLOITS"), 0, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_MPPLY_ISPUNISHED"), 0, true)
-- Star and Time Fix. Both of these can be removed or commented out if you're comfortable with your time or did not do the RP generator method.
-- Playtime edits. Be sure to adjust this to what you'd like. It has a maximum of 23 days worth.. being a 32-bit value. If you want to pass that you'll need to use STAT_SET_INCREMENT. This is defaulted at 9 days 4 hours.
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_TOTAL_PLAYING_TIME"), 792000000, true)
-- Fix for the RP generator's absurd amount of star gain. Adjust the 2043 accordingly to what you want.
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_STARS_ATTAINED"), 2043, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_STARS_EVADED"), 2043, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_NO_TIMES_WANTED_LEVEL"), 2043, true)

        end
		print("You da real MVP now.")
		end
            self:Wait(50)
    end
end

function real_mvp:OnError()
    print("You done failed son!")
    self:Reset()
end

real_mvp:Register()