real_mvp_appearance = ScriptThread("real_mvp_appearance") 


function real_mvp_appearance:Run()
    local playerPedId = {0, 1, 2}
    
    while self:IsRunning() do
        if IsKeyDown(0x67) then
		-- KEY: Numpad7
		for i= 1, 3 do
	--
	
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_ADMIN_CLOTHESGV_BS_3"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_ADMIN_CLOTHES_GV_BS_1"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_ADMIN_CLOTHES_GV_BS_1"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_ADMIN_CLOTHES_GV_BS_10"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_ADMIN_CLOTHES_GV_BS_10"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_ADMIN_CLOTHES_GV_BS_11"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_ADMIN_CLOTHES_GV_BS_11"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_ADMIN_CLOTHES_GV_BS_12"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_ADMIN_CLOTHES_GV_BS_12"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_ADMIN_CLOTHES_GV_BS_13"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_ADMIN_CLOTHES_GV_BS_2"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_ADMIN_CLOTHES_GV_BS_4"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_ADMIN_CLOTHES_GV_BS_5"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_ADMIN_CLOTHES_GV_BS_6"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_ADMIN_CLOTHES_GV_BS_7"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_ADMIN_CLOTHES_GV_BS_8"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_ADMIN_CLOTHES_GV_BS_9"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_BERD"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_BERD_1"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_BERD_2"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_BERD_3"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_BERD_4"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_BERD_5"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_BERD_6"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_BERD_7"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_DECL"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_FEET"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_FEET_1"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_FEET_2"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_FEET_3"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_FEET_4"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_FEET_5"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_FEET_6"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_FEET_7"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_HAIR"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_HAIR_1"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_HAIR_2"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_HAIR_3"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_HAIR_4"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_HAIR_5"), 1, true);
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_HAIR_6"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_HAIR_7"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_JBIB"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_JBIB_1"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_JBIB_2"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_JBIB_3"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_JBIB_4"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_JBIB_5"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_JBIB_6"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_JBIB_7"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_LEGS"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_LEGS_1"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_LEGS_2"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_LEGS_3"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_LEGS_4"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_LEGS_5"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_LEGS_6"), 1, true);
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_LEGS_7"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_OUTFIT"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_PROPS"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_PROPS_1"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_PROPS_10"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_PROPS_2"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_PROPS_3"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_PROPS_4"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_PROPS_5"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_PROPS_6"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_PROPS_7"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_PROPS_8"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_PROPS_9"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_SPECIAL"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_SPECIAL2"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_SPECIAL2_1"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_SPECIAL_1"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_SPECIAL_2"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_SPECIAL_3"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_SPECIAL_4"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_SPECIAL_5"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_SPECIAL_6"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_SPECIAL_7"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_TEETH"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_TEETH_1"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_TEETH_2"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_TORSO"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_BERD"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_BERD_1"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_BERD_2"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_BERD_3"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_BERD_4"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_BERD_5"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_BERD_6"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_BERD_7"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_DECL"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_FEET"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_FEET_1"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_FEET_1"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_FEET_2"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_FEET_3"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_FEET_4"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_FEET_5"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_FEET_6"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_FEET_7"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_HAIR"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_HAIR_1"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_HAIR_2"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_HAIR_3"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_HAIR_4"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_HAIR_5"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_HAIR_6"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_HAIR_7"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_JBIB"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_JBIB_1"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_JBIB_2"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_JBIB_3"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_JBIB_4"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_JBIB_5"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_JBIB_6"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_JBIB_7"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_LEGS"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_LEGS_1"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_LEGS_2"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_LEGS_3"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_LEGS_4"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_LEGS_5"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_LEGS_6"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_LEGS_7"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_OUTFIT"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_PROPS"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_PROPS_1"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_PROPS_10"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_PROPS_2"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_PROPS_3"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_PROPS_4"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_PROPS_5"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_PROPS_6"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_PROPS_7"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_PROPS_8"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_PROPS_9"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_SPECIAL"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_SPECIAL2"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_SPECIAL2_1"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_SPECIAL_1"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_SPECIAL_2"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_SPECIAL_3"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_SPECIAL_4"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_SPECIAL_5"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_SPECIAL_6"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_SPECIAL_7"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_TEETH"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_TEETH_1"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_TEETH_2"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_TORSO"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_DLC_APPAREL_ACQUIRED_0"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_DLC_APPAREL_ACQUIRED_1"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_DLC_APPAREL_ACQUIRED_10"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_DLC_APPAREL_ACQUIRED_11"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_DLC_APPAREL_ACQUIRED_12"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_DLC_APPAREL_ACQUIRED_13"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_DLC_APPAREL_ACQUIRED_14"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_DLC_APPAREL_ACQUIRED_15"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_DLC_APPAREL_ACQUIRED_16"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_DLC_APPAREL_ACQUIRED_17"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_DLC_APPAREL_ACQUIRED_18"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_DLC_APPAREL_ACQUIRED_19"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_DLC_APPAREL_ACQUIRED_2"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_DLC_APPAREL_ACQUIRED_21"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_DLC_APPAREL_ACQUIRED_22"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_DLC_APPAREL_ACQUIRED_23"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_DLC_APPAREL_ACQUIRED_24"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_DLC_APPAREL_ACQUIRED_24"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_DLC_APPAREL_ACQUIRED_25"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_DLC_APPAREL_ACQUIRED_26"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_DLC_APPAREL_ACQUIRED_27"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_DLC_APPAREL_ACQUIRED_28"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_DLC_APPAREL_ACQUIRED_29"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_DLC_APPAREL_ACQUIRED_3"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_DLC_APPAREL_ACQUIRED_30"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_DLC_APPAREL_ACQUIRED_31"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_DLC_APPAREL_ACQUIRED_32"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_DLC_APPAREL_ACQUIRED_33"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_DLC_APPAREL_ACQUIRED_34"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_DLC_APPAREL_ACQUIRED_35"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_DLC_APPAREL_ACQUIRED_36"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_DLC_APPAREL_ACQUIRED_37"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_DLC_APPAREL_ACQUIRED_38"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_DLC_APPAREL_ACQUIRED_39"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_DLC_APPAREL_ACQUIRED_4"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_DLC_APPAREL_ACQUIRED_40"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_DLC_APPAREL_ACQUIRED_5"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_DLC_APPAREL_ACQUIRED_6"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_DLC_APPAREL_ACQUIRED_7"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_DLC_APPAREL_ACQUIRED_8"), 1, true)
					natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_DLC_APPAREL_ACQUIRED_9"), 1, true)
					
	-- End of hashes.

        end
		print("You have successfully applied DLC apparel, normal apparel, beards, and etc to your character.")
		end
            self:Wait(50)
    end
end

function real_mvp_appearance:OnError()
    print("You done failed son!")
    self:Reset()
end

real_mvp_appearance:Register()