real_mvp = ScriptThread("real_mvp") 


function real_mvp:Run()
    local playerPedId = {0, 1, 2}
    
    while self:IsRunning() do
        if IsKeyDown(0x60) then
		-- KEY: Numpad0
		for i= 1, 3 do
print("Converting stats and unlocks...")
-- Level Stat. This is based on the amount of XP per level. It will now apply global XP. Do note that if you have several characters you will need to combine all of their XP earned for your correct global XP value.
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CHAR_XP_FM"), 2284550, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MPPLY_GLOBALXP"), 2284550, true)
-- Unlocks and achievements.
natives.STATS.STAT_SET_BOOL(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_AWD_FMATTGANGHQ"), true, true)
natives.STATS.STAT_SET_BOOL(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_AWD_FMFULLYMODDEDCAR"), true, true)
natives.STATS.STAT_SET_BOOL(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_AWD_FMKILL3ANDWINGTARACE"), true, true)
natives.STATS.STAT_SET_BOOL(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_AWD_FMMOSTKILLSSURVIVE"), true, true)
natives.STATS.STAT_SET_BOOL(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_AWD_FMPICKUPDLCCRATE1ST"), true, true)
natives.STATS.STAT_SET_BOOL(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_AWD_FMRACEWORLDRECHOLDER"), true, true)
natives.STATS.STAT_SET_BOOL(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_AWD_FMWINALLRACEMODES"), true, true)
natives.STATS.STAT_SET_BOOL(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_AWD_FMWINEVERYGAMEMODE"), true, true)
natives.STATS.STAT_SET_BOOL(natives.GAMEPLAY.GET_HASH_KEY("MPPLY_CHAR_IS_BADSPORT"), false, true)
natives.STATS.STAT_SET_FLOAT(natives.GAMEPLAY.GET_HASH_KEY("MPPLY_OVERALL_BADSPORT"), 0, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_ADVRIFLE_ENEMY_KILLS"), 600, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_ADVRIFLE_KILLS"), 600, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_APPISTOL_ENEMY_KILLS"), 600, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_APPISTOL_KILLS"), 600, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_ASLTRIFLE_ENEMY_KILLS"), 600, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_ASLTRIFLE_KILLS"), 600, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_ASLTSHTGN_ENEMY_KILLS"), 600, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_ASLTSHTGN_KILLS"), 600, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_ASLTSMG_ENEMY_KILLS"), 600, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_ASLTSMG_KILLS"), 600, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_AWD_20_KILLS_MELEE"), 50, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_AWD_25_KILLS_STICKYBOMBS"), 50, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_AWD_50_KILLS_GRENADES"), 50, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_AWD_CAR_BOMBS_ENEMY_KILLS"), 25, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_AWD_ENEMYDRIVEBYKILLS"), 600, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_AWD_FMBBETWIN"), 50000, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_AWD_FMHORDWAVESSURVIVE"), 21, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_AWD_FMKILLBOUNTY"), 50, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_AWD_FMRALLYWONDRIVE"), 10,true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_AWD_FMRALLYWONDRIVE"), 2, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_AWD_FMREVENGEKILLSDM"), 60, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_AWD_FMWINAIRRACE"), 2, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_AWD_FMWINSEARACE"), 10,true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_AWD_FM_DM_TOTALKILLS"), 500, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_AWD_FM_DM_WINS"), 63, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_AWD_FM_GOLF_WON"), 2, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_AWD_FM_GTA_RACES_WON"), 12, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_AWD_FM_RACES_FASTEST_LAP"), 101, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_AWD_FM_SHOOTRANG_CT_WON"), 2, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_AWD_FM_SHOOTRANG_GRAN_WON"), 2, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_AWD_FM_SHOOTRANG_RT_WON"), 2, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_AWD_FM_SHOOTRANG_TG_WON"), 2, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_AWD_FM_TDM_MVP"), 60, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_AWD_FM_TDM_WINS"), 13, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_AWD_FM_TENNIS_WON"), 2, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_AWD_HOLD_UP_SHOPS"), 20, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_AWD_NO_ARMWRESTLING_WINS"), 21, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_AWD_RACES_WON"), 101, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_AWD_SECURITY_CARS_ROBBED"), 40, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CMBTMG_ENEMY_KILLS"), 600, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CMBTMG_KILLS"), 600, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CMBTPISTOL_ENEMY_KILLS"), 600, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CMBTPISTOL_KILLS"), 600, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CRBNRIFLE_ENEMY_KILLS"), 600, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CRBNRIFLE_KILLS"), 600, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_DB_PLAYER_KILLS"), 1000, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_GRENADE_ENEMY_KILLS"), 50, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_GRNLAUNCH_ENEMY_KILLS"), 600, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_GRNLAUNCH_KILLS"), 600, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_HVYSNIPER_ENEMY_KILLS"), 600, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_HVYSNIPER_KILLS"), 600, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_KILLS_PLAYERS"), 1000, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_LAP_DANCED_BOUGHT"), 50, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_MG_ENEMY_KILLS"), 600, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_MG_KILLS"), 600, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_MICROSMG_ENEMY_KILLS"), 600, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_MICROSMG_KILLS"), 600, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_MINIGUNS_ENEMY_KILLS"), 600, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_MINIGUNS_KILLS"), 600, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_NUMBER_SLIPSTREAMS_IN_RACE"), 110,true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_NUMBER_TURBO_STARTS_IN_RACE"), 100, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_PISTOL_ENEMY_KILLS"), 600, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_PISTOL_KILLS"), 600, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_PLAYER_HEADSHOTS"), 623, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_PUMP_ENEMY_KILLS"), 600, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_PUMP_KILLS"), 600, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_RACES_WON"), 100, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_RACES_WON"), 50,true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_RPG_ENEMY_KILLS"), 600, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_RPG_KILLS"), 600, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_SAWNOFF_ENEMY_KILLS"), 600, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_SMG_ENEMY_KILLS"), 600, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_SMG_KILLS"), 600, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_SNIPERRFL_ENEMY_KILLS"), 600, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_SNIPERRFL_KILLS"), 600, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_USJS_COMPLETED"), 50, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_USJS_FOUND"), 50,true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MPPLY_DM_TOTAL_DEATHS"), 412, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MPPLY_TENNIS_MATCHES_WON"), 2, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MPPLY_TIMES_FINISH_DM_TOP_3"), 36, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MPPLY_TIMES_RACE_BEST_LAP"), 101, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MPPLY_TOTAL_DEATHMATCH_LOST"), 23, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MPPLY_TOTAL_RACES_LOST"), 36, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MPPLY_TOTAL_RACES_WON"), 101, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MPPLY_TOTAL_TDEATHMATCH_WON"), 63, true)

-- Bad Sport Shit
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_BAD_SPORT_BITSET"), 0, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CHEAT_BITSET"), 0, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MPPLY_BECAME_BADSPORT_NUM"), 0, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MPPLY_COMMEND_STRENGTH"), 100, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MPPLY_FRIENDLY"), 100, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MPPLY_GAME_EXPLOITS"), 0, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MPPLY_GRIEFING"), 0, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MPPLY_HELPFUL"), 100, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MPPLY_ISPUNISHED"), 0, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MPPLY_OFFENSIVE_LANGUAGE"), 0, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MPPLY_OFFENSIVE_UGC"), 0, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MPPLY_OVERALL_CHEAT"), 0, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MPPLY_REPORT_STRENGTH"), 32, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MPPLY_VC_HATE"), 0, true)
-- Star and Time Fix. Both of these can be removed or commented out if you're comfortable with your time or did not do the RP generator method.
-- Playtime edits. Be sure to adjust this to what you'd like. It has a maximum of 23 days worth.. being a 32-bit value. If you want to pass that you'll need to use STAT_SET_INCREMENT. This is defaulted at 9 days 4 hours.
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_TOTAL_PLAYING_TIME"), 792000000, true)
-- Fix for the RP generator's absurd amount of star gain. Adjust the 2043 accordingly to what you want.
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_STARS_ATTAINED"), 2043, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_STARS_EVADED"), 2043, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_NO_TIMES_WANTED_LEVEL"), 2043, true)
-- Added clothing to this section here.
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_ADMIN_CLOTHESGV_BS_3"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_ADMIN_CLOTHES_GV_BS_1"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_ADMIN_CLOTHES_GV_BS_1"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_ADMIN_CLOTHES_GV_BS_10"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_ADMIN_CLOTHES_GV_BS_10"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_ADMIN_CLOTHES_GV_BS_11"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_ADMIN_CLOTHES_GV_BS_11"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_ADMIN_CLOTHES_GV_BS_12"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_ADMIN_CLOTHES_GV_BS_12"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_ADMIN_CLOTHES_GV_BS_13"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_ADMIN_CLOTHES_GV_BS_2"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_ADMIN_CLOTHES_GV_BS_4"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_ADMIN_CLOTHES_GV_BS_5"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_ADMIN_CLOTHES_GV_BS_6"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_ADMIN_CLOTHES_GV_BS_7"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_ADMIN_CLOTHES_GV_BS_8"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_ADMIN_CLOTHES_GV_BS_9"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_BERD"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_BERD_1"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_BERD_2"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_BERD_3"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_BERD_4"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_BERD_5"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_BERD_6"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_BERD_7"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_DECL"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_FEET"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_FEET_1"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_FEET_2"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_FEET_3"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_FEET_4"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_FEET_5"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_FEET_6"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_FEET_7"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_HAIR"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_HAIR_1"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_HAIR_2"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_HAIR_3"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_HAIR_4"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_HAIR_5"), 1, true);
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_HAIR_6"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_HAIR_7"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_JBIB"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_JBIB_1"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_JBIB_2"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_JBIB_3"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_JBIB_4"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_JBIB_5"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_JBIB_6"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_JBIB_7"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_LEGS"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_LEGS_1"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_LEGS_2"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_LEGS_3"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_LEGS_4"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_LEGS_5"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_LEGS_6"), 1, true);
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_LEGS_7"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_OUTFIT"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_PROPS"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_PROPS_1"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_PROPS_10"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_PROPS_2"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_PROPS_3"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_PROPS_4"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_PROPS_5"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_PROPS_6"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_PROPS_7"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_PROPS_8"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_PROPS_9"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_SPECIAL"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_SPECIAL2"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_SPECIAL2_1"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_SPECIAL_1"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_SPECIAL_2"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_SPECIAL_3"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_SPECIAL_4"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_SPECIAL_5"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_SPECIAL_6"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_SPECIAL_7"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_TEETH"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_TEETH_1"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_TEETH_2"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_ACQUIRED_TORSO"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_BERD"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_BERD_1"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_BERD_2"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_BERD_3"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_BERD_4"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_BERD_5"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_BERD_6"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_BERD_7"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_DECL"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_FEET"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_FEET_1"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_FEET_1"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_FEET_2"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_FEET_3"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_FEET_4"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_FEET_5"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_FEET_6"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_FEET_7"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_HAIR"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_HAIR_1"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_HAIR_2"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_HAIR_3"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_HAIR_4"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_HAIR_5"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_HAIR_6"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_HAIR_7"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_JBIB"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_JBIB_1"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_JBIB_2"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_JBIB_3"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_JBIB_4"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_JBIB_5"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_JBIB_6"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_JBIB_7"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_LEGS"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_LEGS_1"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_LEGS_2"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_LEGS_3"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_LEGS_4"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_LEGS_5"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_LEGS_6"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_LEGS_7"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_OUTFIT"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_PROPS"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_PROPS_1"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_PROPS_10"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_PROPS_2"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_PROPS_3"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_PROPS_4"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_PROPS_5"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_PROPS_6"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_PROPS_7"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_PROPS_8"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_PROPS_9"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_SPECIAL"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_SPECIAL2"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_SPECIAL2_1"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_SPECIAL_1"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_SPECIAL_2"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_SPECIAL_3"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_SPECIAL_4"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_SPECIAL_5"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_SPECIAL_6"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_SPECIAL_7"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_TEETH"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_TEETH_1"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_TEETH_2"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CLTHS_AVAILABLE_TORSO"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_DLC_APPAREL_ACQUIRED_0"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_DLC_APPAREL_ACQUIRED_1"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_DLC_APPAREL_ACQUIRED_10"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_DLC_APPAREL_ACQUIRED_11"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_DLC_APPAREL_ACQUIRED_12"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_DLC_APPAREL_ACQUIRED_13"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_DLC_APPAREL_ACQUIRED_14"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_DLC_APPAREL_ACQUIRED_15"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_DLC_APPAREL_ACQUIRED_16"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_DLC_APPAREL_ACQUIRED_17"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_DLC_APPAREL_ACQUIRED_18"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_DLC_APPAREL_ACQUIRED_19"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_DLC_APPAREL_ACQUIRED_2"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_DLC_APPAREL_ACQUIRED_21"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_DLC_APPAREL_ACQUIRED_22"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_DLC_APPAREL_ACQUIRED_23"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_DLC_APPAREL_ACQUIRED_24"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_DLC_APPAREL_ACQUIRED_24"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_DLC_APPAREL_ACQUIRED_25"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_DLC_APPAREL_ACQUIRED_26"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_DLC_APPAREL_ACQUIRED_27"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_DLC_APPAREL_ACQUIRED_28"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_DLC_APPAREL_ACQUIRED_29"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_DLC_APPAREL_ACQUIRED_3"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_DLC_APPAREL_ACQUIRED_30"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_DLC_APPAREL_ACQUIRED_31"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_DLC_APPAREL_ACQUIRED_32"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_DLC_APPAREL_ACQUIRED_33"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_DLC_APPAREL_ACQUIRED_34"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_DLC_APPAREL_ACQUIRED_35"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_DLC_APPAREL_ACQUIRED_36"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_DLC_APPAREL_ACQUIRED_37"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_DLC_APPAREL_ACQUIRED_38"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_DLC_APPAREL_ACQUIRED_39"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_DLC_APPAREL_ACQUIRED_4"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_DLC_APPAREL_ACQUIRED_40"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_DLC_APPAREL_ACQUIRED_5"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_DLC_APPAREL_ACQUIRED_6"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_DLC_APPAREL_ACQUIRED_7"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_DLC_APPAREL_ACQUIRED_8"), 1, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_DLC_APPAREL_ACQUIRED_9"), 1, true)
-- Snacks and Armor
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CHAR_ARMOUR_1_COUNT"), 420, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CHAR_ARMOUR_2_COUNT"), 420, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CHAR_ARMOUR_3_COUNT"), 420, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CHAR_ARMOUR_4_COUNT"), 420, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CHAR_ARMOUR_5_COUNT"), 420, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_CIGARETTES_BOUGHT"), 420, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_FIREWORK_TYPE_1_BLUE"), 420, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_FIREWORK_TYPE_1_RED"), 420, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_FIREWORK_TYPE_1_WHITE"), 420, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_FIREWORK_TYPE_2_BLUE"), 420, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_FIREWORK_TYPE_2_RED"), 420, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_FIREWORK_TYPE_2_WHITE"), 420, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_FIREWORK_TYPE_3_BLUE"), 420, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_FIREWORK_TYPE_3_RED"), 420, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_FIREWORK_TYPE_3_WHITE"), 420, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_FIREWORK_TYPE_4_BLUE"), 420, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_FIREWORK_TYPE_4_RED"), 420, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_FIREWORK_TYPE_4_WHITE"), 420, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_NO_BOUGHT_EPIC_SNACKS"), 420, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_NO_BOUGHT_HEALTH_SNACKS"), 420, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_NO_BOUGHT_YUM_SNACKS"), 420, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_NUMBER_OF_BOURGE_BOUGHT"), 420, true)
natives.STATS.STAT_SET_INT(natives.GAMEPLAY.GET_HASH_KEY("MP" .. playerPedId[i] .. "_NUMBER_OF_ORANGE_BOUGHT"), 420, true)
-- End of hashes.

        end
		print("You da real MVP now.")
		end
            self:Wait(50)
    end
end

function real_mvp:OnError()
    print("You done failed son!")
    self:Reset()
end

real_mvp:Register()